branch-defaults:
  p2_solution:
    environment: amazon-keyword-estimate
    ec2_keyname: amazon-keyword-estimate

global:
  application_name: Amazon-Keyword-Estimate
  default_platform: Multi-container Docker running on 64bit Amazon Linux/2.11.0
  default_region: us-east-2
  sc: git
