branch-defaults:
  p2_solution:
    environment: amazon-keyword-estimate
    ec2_keyname: amazon-keyword-estimate

global:
  application_name: Amazon-Keyword-Estimate
  default_platform: 64bit Amazon Linux 2018.03 v2.10.0 running Multi-container Docker 17.12.1-ce (Generic)
  default_region: us-west-2
  sc: git
