branch-defaults:
  p2_solution:
    environment: amazon-keyword-estimate
    ec2_keyname: amazon-keyword-estimate

global:
  application_name: Amazon-Keyword-Estimate
  default_platform: Multi-container Docker 18.03.1-ce (Generic)
  default_region: us-east-1
  sc: git
